name: Create Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Zip Files
        run: |
          zip -r release.zip ./* -x "src/popup/src/*" "src/popup/public/*" "src/popup/*.*" ".git/*" ".github/*"

      - name: Create Release
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: release.zip
