name: Create Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: |
            Description of the release.

      - name: Exclude Unwanted Files
        run: |
          # Create a temporary directory
          mkdir temp_release
          
          # Copy everything except /src/popup/src to the temporary directory
          rsync -av --progress --exclude='src/popup/src' ./ temp_release/
          
          # Zip the contents of the temporary directory
          zip -r release.zip temp_release/
          
          # Move the ZIP file to the repository root
          mv release.zip ./zip
          
          # Clean up
          rm -rf temp_release

      - name: Create Release
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: ./zip
