name: Create releases

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compress Chromium build
        run: |
          zip -r chromium.zip ./* -x "src/popup/src/*" "src/popup/public/*" "src/popup/*.*" ".git/*" ".github/*" "manifest-firefox.json"

      - name: Compress Firefox build
        run: |
          mv manifest.json manifest-chromium.json
          mv manifest-firefox.json manifest.json
          zip -r firefox.zip ./* -x "src/popup/src/*" "src/popup/public/*" "src/popup/*.*" ".git/*" ".github/*" "manifest-chromium.json" "chromium.zip
          mv manifest.json manifest-firefox.json
          mv manifest-chromium.json manifest.json

      - name: Upload as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Releases
          path: |
            chromium.zip
            firefox.zip
